### PR TITLE
Move the intent recipient to a second (external) activity on Android.

### PR DESCRIPTION
**Pull request by bytex64**
This requires that your app implements an activity called "SecondActivty". The
intent will be sent to it rather than the default MainActivity. This can be
used to implement a pop-up sheet dialog for accepting the share.

### CODE REVIEW

**Comment by franc5** [comment]
Don't we have to also revert https://github.com/SpiderOak/cordova-plugin-openwith/pull/1?

**Comment by bytex64** [comment]
> Don't we have to also revert #1?

I don't think it's strictly necessary for this to work (this should turn #1 into dead code), but I guess it's probably a good idea.

**Comment by franc5** [comment]
> I don't think it's strictly necessary for this to work (this should turn #1 into dead code), but I guess it's probably a good idea.

I was editing my comment when you answered. There's some extra info now.

**Comment by bytex64** [comment]
> I've checked what happen if we revert #1 and after sharing a file from MSWord and then a file from my gallery app I ended up with two CC instances, one with a MainActivity and a second one with a "SecondActivity". I was expecting the "SecondActivity" to be finished automatically. Could "SecondActivity" remain "unfinished" somehow?

In the original test implementation in the `second-activity` branch, SecondActivity doesn't close itself. If you're using the one in the ticket branch (the "new intent receiver"), it should close itself. (Really, it should never appear in the first place because it closes itself in response to `onCreate`) I don't think #1 makes a difference for that behavior.

**Review by ivanalejandro0 — APPROVED** [review]
This does the work.
I think we may want to update the README file to explain the changes we are introducing on this plugin over time ("Fork updates" or something), so we'll have documentation of what's changed.

**Pull request merged**
